### ISSUE TITLE
How to get the cam1_to_world.txt file

### ISSUE THREAD

**Issue by booker-max** [autonomousvision/kitti360Scripts#101]
In the data_poses folder, there is only the **cam0_to_world.txt** file in each scene, how to get the cam1_to_world.txt file, currently I pass

T = np.array([[1, 0, 0, 0.6],

[0, 1, 0, 0],

[0, 0, 1, 0],

[0, 0, 0, 1]]).astype(np.float32)

**cam1_to_world** = cam0_to_world @ T get **cam1_to_world**, is this reasonable, thank you.

**Comment by yiyiliao** [comment]
Hi, here we provide scripts to calculate cam2world for all cameras:
https://github.com/autonomousvision/kitti360Scripts/blob/9defe218f4d05a1c920924f38ebfa8efc27318da/kitti360scripts/helpers/project.py#L21-L43
