### ISSUE TITLE
Question about velodyne point cloud's ground truth pose.

### ISSUE THREAD

**Issue by ZhangZh3ng** [autonomousvision/kitti360Scripts#102]
Hello, I am trying to obtain the true pose of each Velodyne point cloud frame. However, I am confused about the ground true pose's frame ID and the Velodyne LiDAR point cloud's .bin ID.

In cam0_to_world.txt and pose.txt the first column is an integer that indicate the frame ID, and it seems always start from 1. While in the velodyne_points/data/, the bin file's ID always start from 0000000000.bin. So I want know if it is right: the ground truth pose of velodyne 0000000000.bin is the first row in the pose file(frame ID = 1), and so on (00000000060.bin's pose is the line which frame ID = 61 in pose file)

By the way, since some frames have missing ground true values, is it reasonable to try using linear interpolation methods to obtain these missing items?

**Comment by yiyiliao** [comment]
Thank you for your question. The frame ID follows zero-based indexing, meaning that the ground truth pose of velodyne 0000000001.bin is the row with frame ID = 1.

> By the way, since some frames have missing ground true values, is it reasonable to try using linear interpolation methods to obtain these missing items?

We do not provide poses for some frames only when the vehicle is moving at a very slow speed. It should be reasonable to use linear interpolation methods to obtain these missing items. You may also use the `OXTS Raw Measurements (0.4G)` to help with the interpolation.
