### ISSUE TITLE
Is there are fisheye images at your val dataset?

### ISSUE THREAD

**Issue by whu-lyh** [autonomousvision/kitti360Scripts#105]
The title pretty much represents the question. I wonder whether there are fisheye images in your val dataset, split as your paper writes. Thanks @yiyiliao

**Comment by yiyiliao** [comment]
Hi, which benchmark are you referring to regarding the train/val split? We provide train/val split in terms of frame IDs, meaning that splitting the fisheye images in the same way should be possible. However, we do not provide 2D labels for fisheye images currently.

**Comment by whu-lyh** [comment]
Thanks
