### ISSUE TITLE
Question about the label quality

### ISSUE THREAD

**Issue by placeforyiming** [autonomousvision/kitti360Scripts#13]
Thanks for your hard work to share this detailed dataset.
However, I found some of the semantic labels are not accurate, here is an example:

![Screenshot from 2021-01-06 18-33-08](https://user-images.githubusercontent.com/22132384/103833618-69a52080-504f-11eb-97ec-669271697684.png)

Those semantic labels seem are model-generated or mapped from the 3D point cloud. So my question is, which part of the labeling is most trustworthy? Those 3D point cloud labels?

**Comment by yiyiliao** [comment]
Hi @placeforyiming , thanks for the question! Our 2D labels are obtained by transferring coarse 3D annotations to 2D using CRF which naturally models the uncertainty of the prediction. The labels at the more confident region are more trustworthy (see the bottom half of Table 2 in the [paper](http://ww.w.cvlibs.net/publications/Xie2016CVPR.pdf). You can find the confidence maps on our download page.
