### ISSUE TITLE
Is the 3Dbox size obtained from data_3d_bbboxes  annotation file  accurate？

### ISSUE THREAD

**Issue by tianjun-world** [autonomousvision/kitti360Scripts#130]
Hello, the 3Dbox size obtained from data_3d_bbboxes is different from the actual size. The length, width, and height of the data_3d_bbboxes annotation file are constant

**Comment by yiyiliao** [comment]
The sizes of the 3D bounding boxes are precise. The length, width, and height are captured in the `transform` matrix, which is a product of the rotation matrix (R) and a diagonal scaling matrix (S). The diagonal scaling matrix S contains the length, width, and height values. Here is the script for loading the 3D bounding boxes:
https://github.com/autonomousvision/kitti360Scripts/blob/9defe218f4d05a1c920924f38ebfa8efc27318da/kitti360scripts/helpers/annotation.py#L125-L136
