### ISSUE TITLE
Label discrepancy

### ISSUE THREAD

**Issue by pimonteiro** [autonomousvision/kitti360Scripts#14]
Hello! Before anything, what a great work you did!
My question: upon analysing the labels from the segmentation mask, i noticed that more labels exists than the cityscapes. Being more specific, i noticed there are extra classes, from 34 to 39. Can you explain me why do these exist while you specified making the dataset in accordance to the cityscapes format?

Thank you!

Edit: I noticed that the label for the class 39 is missing on the helper function. What does this represent?

**Comment by pimonteiro** [comment]
![download](https://user-images.githubusercontent.com/25423909/105742792-dbc4a300-5f33-11eb-8a8a-998629eee2a2.png)

For example, on the image above, there is a class 35 on the red portion of the image (I assume it points to some sort of gate, just behind the car).

**Comment by pimonteiro** [comment]
I apologize for my lack of understanding of the paper and the code provided in this github. After carefully analysing it I finally understood the label system.

**Comment by yiyiliao** [comment]
Hi @pimonteiro, thanks for your question! We indeed have more classes than Cityscapes as we annotated in that way, i.e., we have a few more classes such as "garage". We plan to use the same set of labels for training and evaluations though. Great that you figured it out already, feel free to let me know if there is anything we should improve regarding the paper or the code.
