### ISSUE TITLE
mismatch when project velodyne to image

### ISSUE THREAD

**Issue by linbaiwpi** [autonomousvision/kitti360Scripts#18]
hello when projecting the velodyne into image plane, I found some mismatch between image and verlodyne. While this is not found in KITTI dataset. How can I rectify the data?

P.S. I calculate the velo2img matrix by inverse the img2velo matrix

**Comment by yiyiliao** [comment]
Hi @linbaiwpi, thanks for the question. We have now added a demo to project velodyne data to the image space: https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/viewer/kitti360Viewer3DRaw.py#L66. You can change the image ID to project velodyne points to perspective or fisheye images.

Note that compared to KITTI, the sensors are mounted in a different setting in KITTI-360. In particular, the velodyne scanner is mounted further away from the perspective cameras. This might lead to the impression of misalignment in the image space as some points are occluded in the image space while visible to the Velodyne scanner. 

Feel free to reopen the issue if you have further questions.
