### ISSUE TITLE
方便提供一下标注工具不

### ISSUE THREAD

**Issue by zyxcambridge** [autonomousvision/kitti360Scripts#2]
It is convenient to provide the marking tool

**Comment by yiyiliao** [comment]
Yes we plan to make the annotation tool publicly available. We will release the tool once the code is cleaned.

**Comment by zyxcambridge** [comment]
> Yes we plan to make the annotation tool publicly available. We will release the tool once the code is cleaned.

thanks ,but now , code can send to me by gmail zyxcambridge@gmail.com, i will give my advise

**Comment by yiyiliao** [comment]
Hi, our annotation tool is now available online:
https://github.com/autonomousvision/kitti360labeltool
