### ISSUE TITLE
List of labels for bounding boxe annotations

### ISSUE THREAD

**Issue by nlgranger** [autonomousvision/kitti360Scripts#20]
The labels for the bounding boxes annotations do not seem to match the list in https://github.com/autonomousvision/kitti360Scripts/blob/b74933bb4d358d4b8f4c371528f036be2092060c/kitti360scripts/helpers/labels.py which is for semantic annotations For instance, this list does not mention "Big Pole"

**Comment by yiyiliao** [comment]
Hi @nlgranger, thanks for the feedback! It is true that the label names of a few classes are slightly inconsistent but the indices should match. For example, the "semanticId" of "bigPole" in the bounding box annotations (*.xml) is 21, which is referred to "pole" according to its "kittiId" https://github.com/autonomousvision/kitti360Scripts/blob/b74933bb4d358d4b8f4c371528f036be2092060c/kitti360scripts/helpers/labels.py#L83.
Sorry for the inconsistency. We will improve this in our future release.

**Comment by nlgranger** [comment]
All right, thanks for the clarification.
