### ISSUE TITLE
Module not Found 'kitti360scripts.devkits'

### ISSUE THREAD

**Issue by resha1417** [autonomousvision/kitti360Scripts#21]
Hello dear all,

Thank you for the great work. I am trying to visualize fused 3D point clouds with labels. I installed all the dependencies. but when I am trying to run ........
cd kitti360scripts/viewer
python kitti360Viewer3D.py -sequence ${sequence}

I am getting error regarding to module not found. 
This is an error I am getting..
Command: python kitti360Viewer3D.py -sequence 2013_05_28_drive_0000_sync

Traceback (most recent call last):
  File "kitti360Viewer3D.py", line 47, in <module>
    from kitti360scripts.helpers.project     import Camera
  File "/home/resha/new_script_360/lib/python3.6/site-packages/kitti360scripts/helpers/project.py", line 6, in <module>
    from kitti360scripts.devkits.commons.loadCalibration import loadCalibrationCameraToPose
ModuleNotFoundError: No module named 'kitti360scripts.devkits'

Please let me know if you have any idea about the error or am I missing something?

**Comment by yiyiliao** [comment]
Hi @resha1417, thanks for reporting the bug! It should be fixed now. Feel free to let us know if you have further questions.
