### ISSUE TITLE
Calibration File for VelotoCam...

### ISSUE THREAD

**Issue by resha1417** [autonomousvision/kitti360Scripts#22]
Hello dear all,

Thank you for the great work. could you let me know how can I get the calibration file for velo2img? I wanted to project velodyne data to corresponding image.

Thanks,
Resha Thacker

**Comment by yiyiliao** [comment]
Hi @resha1417, thanks for the question. We have now added a demo to project velodyne data to the image space: https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/viewer/kitti360Viewer3DRaw.py#L66. Note that you can change the image ID to project velodyne points to perspective or fisheye images.
