### ISSUE TITLE
2d semantic labels

### ISSUE THREAD

**Issue by yshen47** [autonomousvision/kitti360Scripts#32]
Hi there,
Thanks for your help first! I notice that the 2d_semantic data that i downloaded from the KITTI360 website does not follow the data structure provided in the website. In particular, is the semantic labels provided based on the the image_00 or image_01?

Yuan

**Comment by yiyiliao** [comment]
Thanks for pointing out the problem of the data structure! We will fix it soon. The semantic labels provided are based on image_00.

**Comment by yiyiliao** [comment]
Closing now as the semantic labels of image_01 have been released.
