### ISSUE TITLE
Where are the labels for Semantic Scene Completion task?

### ISSUE THREAD

**Issue by anhquancao** [autonomousvision/kitti360Scripts#33]
Hello,
Thank you for creating a great dataset!
I would like to ask where to download the label for the Semantic Scene Completion task?
Thank you again,
Anh-Quan Cao

**Comment by anhquancao** [comment]
Hi @yiyiliao,
I am sorry for bothering you again. Is there any news on the Semantic Scene Completion labels?
Thank you,
Quan

**Comment by yiyiliao** [comment]
Hi, sorry for the delay! I can send you the (uncleaned) script for generating the Semantic Scene Completion labels from the full sequence if it is urgent.

**Comment by anhquancao** [comment]
Hi @yiyiliao,
It would be great!   
Could you send to my email anh-quan.cao@inria.fr?
Thank you a lot for your help
Anh-Quan Cao
