### ISSUE TITLE
Timestamps of accumulated dynamic point clouds

### ISSUE THREAD

**Issue by finnSartoris** [autonomousvision/kitti360Scripts#45]
If I understood correctly, the timestamps in data_3d_semantics/train/2013_05_28_drive_{seq: 0>4}_sync/dynamic/{start_frame: 0>10}_{end_frame: 0>10}.ply denote the frame ID for the dynamic objects.
However, these timestamps do not always match the file names. As an example in the file 0000000002_0000000282.ply in sequence 3 there are points which have timestamps beyond 282 up to 301. Did I misinterpret the timestamps or were the points that have a timestamp beyond 282 appended to the wrong .ply file.
Thanks for your work!

**Comment by yiyiliao** [comment]
Hi, thank you for pointing out the issue! Your interpretation of the timestamps is correct. One ply file may contain points beyond the `end_frame` if the same dynamic object (i.e., object with the same instance ID) remains visible at the beginning of the subsequent ply file. We group dynamic objects according to their instance IDs.
