### ISSUE TITLE
Can Velodyne scans and SICK scans be used for fisheye depth estimation?

### ISSUE THREAD

**Issue by bachtx12** [autonomousvision/kitti360Scripts#47]
Currently, I want to do monocular fisheye depth estimation, but don't have any public dataset. Therefore, I have some questions for you.
1. Can Velodyne scans and SICK scans be used for fisheye depth estimation?
2. if yes. do you have any plan to do that?

Thank you.

**Comment by yiyiliao** [comment]
Hi @bachtx12, thanks for the question. It is possible to project the Velodyne and SICK scans to the fisheye camera. However, we do not have a high-quality mesh for occlusion check, i.e., to filter out occluded points. Therefore these projected points cannot be used directly for monocular fisheye depth estimation unfortunately.
