### ISSUE TITLE
How to do calibration of the ‘cam_to_pos’?

### ISSUE THREAD

**Issue by saedrna** [autonomousvision/kitti360Scripts#49]
I am curious about how the `cam_to_pos` is determined. I think this is related to the documentation as below?

```We obtain accurate georegistered vehicle poses using structure-from-motion based on all feature matches while regularizing against the GPS location and the LiDAR scans. We also release raw OXTS (GPS/IMU) measurements. Note that the poses obtained from structure-from-motion are not identical to the raw OXTS measurements.```

Are ground control points used in the SFM step and then average the calibration between camera POS and GPS/IMU POS according to the same timestamp?

**Comment by yiyiliao** [comment]
Hi, sorry for the late reply. To calibrate `cam_to_pos`, we recorded trajectories of the camera (visual odometry) and the GPS/IMU, and then solved an optimization problem. Here are some [slides](https://github.com/autonomousvision/kitti360Scripts/files/8531283/calibration.pdf) for more details of the calibration.
