### ISSUE TITLE
Mismatch between 2d instance labels and 2d raw images

### ISSUE THREAD

**Issue by MarcusSchilling** [autonomousvision/kitti360Scripts#51]
Hello,

I loaded the 2D instance images and tried to load the corresponding raw images in 2D. In doing so, I noticed that 2D instance maps are available for certain timestamps, but no 2D raw images. Did I do something wrong? 
Here is the list of files:

['0000004461.png', '0000004472.png', '0000004420.png', '0000004479.png', '0000004610.png', '0000004428.png', '0000004486.png', '0000004397.png', '0000004609.png', '0000004399.png', '0000004450.png', '0000004483.png', '0000004391.png', '0000004494.png', '0000004504.png', '0000004541.png', '0000004426.png', '0000004557.png', '0000004422.png', '0000004563.png', '0000004594.png', '0000004595.png', '0000004407.png', '0000004588.png', '0000004412.png', '0000004435.png', '0000004527.png', '0000004495.png', '0000004568.png', '0000004506.png', '0000004470.png', '0000004409.png', '0000004507.png', '0000004545.png', '0000004448.png', '0000004415.png', '0000004416.png', '0000004444.png', '0000004487.png', '0000004528.png', '0000004600.png', '0000004546.png', '0000004583.png', '0000004556.png', '0000004582.png', '0000004540.png', '0000004473.png', '0000004476.png', '0000004603.png', '0000004514.png', '0000004510.png', '0000004489.png', '0000004539.png', '0000004452.png', '0000004608.png', '0000004565.png', '0000004597.png', '0000004612.png', '0000004430.png', '0000004575.png', '0000004436.png', '0000004474.png', '0000004579.png', '0000004446.png', '0000004464.png', '0000004611.png', '0000004513.png', '0000004497.png', '0000004570.png', '0000004574.png', '0000004485.png', '0000004586.png', '0000004522.png', '0000004455.png', '0000004475.png', '0000004578.png', '0000004447.png', '0000004573.png', '0000004559.png', '0000004512.png', '0000004456.png', '0000004533.png', '0000004529.png', '0000004534.png', '0000004601.png', '0000004501.png', '0000004596.png', '0000004478.png', '0000004572.png', '0000004437.png', '0000004521.png', '0000004604.png', '0000004427.png', '0000004419.png', '0000004484.png', '0000004433.png', '0000004477.png', '0000004465.png', '0000004490.png', '0000004442.png', '0000004560.png', '0000004460.png', '0000004605.png', '0000004576.png', '0000004548.png', '0000004551.png', '0000004509.png', '0000004592.png', '0000004463.png', '0000004410.png', '0000004395.png', '0000004458.png', '0000004503.png', '0000004593.png', '0000004552.png', '0000004543.png', '0000004467.png', '0000004531.png', '0000004518.png', '0000004599.png', '0000004398.png', '0000004515.png', '0000004449.png', '0000004481.png', '0000004413.png', '0000004401.png', '0000004598.png', '0000004459.png', '0000004492.png', '0000004451.png', '0000004562.png', '0000004591.png', '0000004432.png', '0000004524.png', '0000004453.png', '0000004438.png', '0000004393.png', '0000004462.png', '0000004585.png', '0000004394.png', '0000004402.png', '0000004571.png', '0000004418.png', '0000004417.png', '0000004400.png', '0000004466.png', '0000004589.png', '0000004439.png', '0000004404.png', '0000004549.png', '0000004408.png', '0000004403.png', '0000004544.png', '0000004469.png', '0000004406.png', '0000004457.png', '0000004468.png', '0000004471.png', '0000004392.png', '0000004536.png', '0000004405.png', '0000004602.png', '0000004414.png', '0000004488.png', '0000004424.png', '0000004537.png', '0000004517.png', '0000004429.png', '0000004542.png', '0000004502.png', '0000004425.png', '0000004538.png', '0000004445.png', '0000004493.png', '0000004443.png', '0000004498.png', '0000004553.png', '0000004411.png', '0000004607.png', '0000004441.png', '0000004567.png', '0000004577.png', '0000004519.png', '0000004491.png', '0000004535.png', '0000004561.png', '0000004554.png', '0000004496.png', '0000004508.png', '0000004482.png', '0000004520.png', '0000004564.png', '0000004505.png', '0000004396.png', '0000004526.png', '0000004581.png', '0000004523.png', '0000004440.png', '0000004511.png', '0000004532.png', '0000004500.png', '0000004566.png', '0000004499.png', '0000004431.png', '0000004525.png', '0000004480.png', '0000004580.png', '0000004587.png', '0000004584.png', '0000004555.png', '0000004547.png', '0000004516.png', '0000004606.png', '0000004454.png', '0000004590.png', '0000004550.png', '0000004423.png', '0000004530.png', '0000004434.png', '0000004558.png', '0000004421.png', '0000004569.png']

Thank you in advance,
Marcus

**Comment by yiyiliao** [comment]
Hi Marcus, thank you for pointing out the mismatch! I have added the missing images to the zip files (2013_05_28_drive_0002_sync_image_{00|01}.zip). The zip files on the AWS will be updated in ~24 hours. You can download them again tomorrow to get the missing files. Sorry for the inconvenience.
