### ISSUE TITLE
[Bug] Visibility Flag is inverted in Sequence 0 for accumulated PCs

### ISSUE THREAD

**Issue by eslambakr** [autonomousvision/kitti360Scripts#54]
Dears,

I have noticed that the visibility flag is inverted in Sequence 0, as shown below:
1) `showVisibleOnly=True`
![image](https://user-images.githubusercontent.com/25908688/163897920-b11157ca-69f3-47dd-b2b0-bcdf96103ae0.png)
2) `showVisibleOnly=False`
![image](https://user-images.githubusercontent.com/25908688/163897982-c8548650-1363-4202-afc4-5f15a330da04.png)

**Comment by yiyiliao** [comment]
Hi, thank you for reporting the problem. This is actually not a bug. This part is not considered `visible` as we do not provide semantic labels for the starting frames of this sequence (0000). Therefore, the 3D semantic label is not retrieved from the corresponding 2D images in this region. Instead, we keep a 3D point only if it is uniquely labeled by a 3D bounding box and assign the label according to the annotation. 

If you check the next window (0000000372_0000000610.ply), the invisible points should be normal (black means points with `visible=0`):
<img width="988" alt="image" src="https://user-images.githubusercontent.com/15853014/164237087-23342195-89e0-49f4-9f21-667801a918ae.png">

**Comment by eslambakr** [comment]
Thank you very much @yiyiliao .
I have verified that for the rest of frames in sequence zero.
Is this behavior should be followed for the rest of sequences?
I mean you do not provide semantic labels for the starting frames of each sequence or sequence zero only?

**Comment by eslambakr** [comment]
Thank you very much for the clarification!
