### ISSUE TITLE
Could you provide the Calibrations(Extrinsics) of velodyne and IMU?

### ISSUE THREAD

**Issue by 0ontheroad** [autonomousvision/kitti360Scripts#56]

**Comment by yiyiliao** [comment]
Hi, you can get the calibration of velodyne and IMU from `calib_cam_to_pose.txt` and `calib_cam_to_velo.txt`, via velo->image_00, image_00->pose (IMU):
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/15853014/167975680-fbfa1f98-269a-41cb-b939-e02aa62ed5e4.png">
