### ISSUE TITLE
Google map

### ISSUE THREAD

**Issue by 0ontheroad** [autonomousvision/kitti360Scripts#59]
Thanks your work a lot. I have a question. When were these datasets recorded. Can you please provide the latitude and longitude coordinates of the recording location.  I want to use google maps to export vector models of these cities, but I don't know the exact location of these recorded places,thank you very much. Best wishes.

**Comment by yiyiliao** [comment]
Hi, the dataset is collected on 28.05.2013. You can find latitude and longitude coordinates in our download page:
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/15853014/170046934-de23177f-54c2-4927-aa49-b4f8f664cab5.png">
