### ISSUE TITLE
imu intrinsics

### ISSUE THREAD

**Issue by 0ontheroad** [autonomousvision/kitti360Scripts#62]
Hi:
   Could you provide the IMU intrinsics, i cound't find it. Thanks a lot!

**Comment by yiyiliao** [comment]
Hi, we used an OXTS 3003 out of the box with the default settings.

**Comment by yiyiliao** [comment]
Hi @huiyan-dev, according to the manual:
https://www.manualslib.com/manual/1952429/Oxts-Rt-Series.html?page=10#manual

> The RT has a high (100 Hz or 250 Hz) update rate and a wide bandwidth.

We used the 100 Hz setting.
