### ISSUE TITLE
Dealing with labels in Accumulated Point Clouds

### ISSUE THREAD

**Issue by vhchuong1997** [autonomousvision/kitti360Scripts#64]
Hello! 
I'm working with the **Accumulated Point Clouds** version of kitti-360. 
This version contains annotated **45 classes**. I am baffled about how to process these classes to create trainable instances and/or ignore some.
Can anyone give some insights or instructions for this type of dataset?
Thank you so much
![Screenshot from 2022-06-24 16-01-02](https://user-images.githubusercontent.com/51077545/175491396-97a0c415-48e3-450e-9f17-834806e745f1.png)
![Screenshot from 2022-06-24 16-02-22](https://user-images.githubusercontent.com/51077545/175491609-97abba62-aafa-4194-8192-e55124591358.png)
!

**Comment by yiyiliao** [comment]
Hi, for creating trainable __semantic__ labels, you can use the [id2trainId](https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/evaluation/semantic_3d/evalPointLevelSemanticLabeling.py#L562-L568) function to convert the original semantic labels to `trainId`. 

For creating trainable __instance__ labels to submit to our evaluation server, you can keep `building` and `car` and ignore the other classes, as we only consider these two classes in our [evaluation script](https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/evaluation/semantic_3d/evalInstanceLevelSemanticLabeling.py#L169).
