### ISSUE TITLE
intensity

### ISSUE THREAD

**Issue by Trent-tangtao** [autonomousvision/kitti360Scripts#69]
Hi, thanks for the excellent work! 
The four dimensions of the points are x, y, z and intensity? as the code [there](https://github.com/autonomousvision/kitti360Scripts/blob/7d44b19446b92801cff403ac0eff5985986ff481/kitti360scripts/viewer/kitti360Viewer3DRaw.py#L53)

**Comment by yiyiliao** [comment]
Thank you for your interest in our dataset!
Yes, the first three dimensions are x, y, z and the fourth is the intensity (reflectivity).

**Comment by Trent-tangtao** [comment]
Got it, thanks!
