### ISSUE TITLE
Problem evaluating scene completion: what is groundTruthFile

### ISSUE THREAD

**Issue by zl3466** [autonomousvision/kitti360Scripts#71]
Hello,
Thanks for making your methods public!
I was trying to run the `evalSceneCompletion.py` script in the `kitti360scripts/evaluation/semantic3d` branch and run into the following problem:
the `getGroundTruth()` function reads a `groundTruthListFile` (named `2013_05_28_drive_val_frame.txt` by default). What exactly should this file be? Is it something that we should generate by ourselves or something readily provided in your download options?

Also, function `generateCroppedGroundTruth()` used a `csWindow` object several times to represent the sequence number and first and last frame number. Is it a self-defined class that should be imported somewhere?

Zhiheng Li

**Comment by yiyiliao** [comment]
Hi, sorry for the late reply!
[Here](https://s3.eu-central-1.amazonaws.com/avg-projects/KITTI-360/data_2d_raw/2013_05_28_drive_val_frames.txt) you can download the `2013_05_28_drive_val_frames.txt`. We also provide indices of training frames [here](https://s3.eu-central-1.amazonaws.com/avg-projects/KITTI-360/data_2d_raw/2013_05_28_drive_train_frames.txt).

The `csWindow` is defined in `csHelpers`:
https://github.com/autonomousvision/kitti360Scripts/blob/00ebfff590dc7ac4d0fb32a3fe8604cb8952700d/kitti360scripts/helpers/csHelpers.py#L93
You may need to reinstall the package if it is cannot be imported.
