### ISSUE TITLE
Question Regarding KITTI LIDAR Intensity 

### ISSUE THREAD

**Issue by yuvalH9** [autonomousvision/kitti360Scripts#73]
Hi,
The raw Velodyne data is given by x y z signal where 'signal' refers to the Lidar intensity.
According to the Velodyne HDL-64E manual the intensity values should be in the range of [0-255], but the actual given values are normalized to [0,1].

My question is what kind of normalization was used? Just division by 255? Or something more sophisticated?

I didn't find any information in the KITTI360 documentation.

Thanks 
Yuval

**Comment by Petros626** [comment]
@yiyiliao correct!

**Comment by Petros626** [comment]
@yiyiliao I got myself question for my project. What is the max intensity and density value from the HDL-64E in the KITTI dataset?

**Comment by Petros626** [comment]
@yiyiliao ?
