### ISSUE TITLE
About gt of test data

### ISSUE THREAD

**Issue by riematrix** [autonomousvision/kitti360Scripts#81]
Hi, 
  How can I evaluate our on real GT for test slam dataset? I didn't find any pose file in the downloaded 4 kitti-360 test sequence.

**Comment by yiyiliao** [comment]
Hi, we do not release GT of test sequences. You can evaluate your method by submitting your results to our evaluation server.

**Comment by riematrix** [comment]
OK, I misunderstood the aim of test data. The package is much smaller than the full dataset so I treat it as a subset, thus don't have to download the big package. Thanks!
