### ISSUE TITLE
Fisheye camera & LiDAR calibration

### ISSUE THREAD

**Issue by HR-zju** [autonomousvision/kitti360Scripts#87]
hi, @pengsongyou @yiyiliao @haofeixu @Pyrestone  
I'm glad you provided such a great dataset!
When I project the laser point cloud onto the fisheye camera image using kitti360Viewer3DRaw.py in the kitti360scripts tool, I find that there are significant offsets, such as the trees and vehicles in the image. What could this be causing?
![4850](https://user-images.githubusercontent.com/73371574/231338118-3cbec750-cded-49bd-9253-1e7ae06e3373.png)
![4850_right](https://user-images.githubusercontent.com/73371574/231338154-82d942ea-58fc-41bd-94e9-fa1a5099812a.png)

**Comment by HR-zju** [comment]
![image](https://user-images.githubusercontent.com/73371574/231338609-a78743a3-a5be-4162-9fd3-13bbe2721fe2.png)

**Comment by HR-zju** [comment]
@yiyiliao @pengsongyou @haofeixu @Pyrestone

**Comment by yiyiliao** [comment]
Hi @HR-zju, thank you for reporting the issue! I am looking into it and will give you an update in 2-3 days.

**Comment by yiyiliao** [comment]
Hi @HR-zju, I've found the problem. The raw velodyne points are not corrected for ego-motion. I have now added the correction code to the visualization script in this [commit](https://github.com/autonomousvision/kitti360Scripts/commit/478aeac239cffdf9858c9079c7d28cb45729362d). This is the result after fixing the problem:
![seq2_cam3_4850](https://user-images.githubusercontent.com/15853014/232735978-89d3e76e-b46a-4e15-9fe9-61819a1319e1.png)

Note that the ego-motion correction was considered in our data accumulation [code](https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/devkits/accumuLaser/src/accumulation.cpp#L450-L461), meaning that the accumulated point clouds are correct.

**Comment by yuliangguo** [comment]
> Hi @HR-zju, I've found the problem. The raw velodyne points are not corrected for ego-motion. I have now added the ego-motion correction code to the visualization script in this [commit](https://github.com/autonomousvision/kitti360Scripts/commit/478aeac239cffdf9858c9079c7d28cb45729362d). This is the result after fixing the problem: ![seq2_cam3_4850](https://user-images.githubusercontent.com/15853014/232735978-89d3e76e-b46a-4e15-9fe9-61819a1319e1.png) <img alt="image" width="1099" src="https://user-images.githubusercontent.com/15853014/232736867-ff6ab76b-32b9-494b-a0bf-d425c7905cc5.png">
> 
> Note that the ego-motion correction was considered in our data accumulation [code](https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/devkits/accumuLaser/src/accumulation.cpp#L450-L461), meaning that the accumulated point clouds are correct.

Thanks for the correction. But there seems still certain offset along the car's border, and something gap on the trees, are they OK?  If I understand correct, some of the error may due to the lidar and came having different centers, thus different visible areas. Is there any way to handle such error?
