### ISSUE TITLE
GPS coordinates

### ISSUE THREAD

**Issue by abmmusa** [autonomousvision/kitti360Scripts#9]
It looks like only poses in the global frame is provided. However, can we get the GPS coordinates as well or is there any way to transform global poses to latitude-longitude coordinates?

**Comment by yiyiliao** [comment]
Thanks for the question! We are working on that and this will be provided soon.

**Comment by yiyiliao** [comment]
We have added the code for converting global poses to latitude-longitude coordinates and vice versa:
https://github.com/autonomousvision/kitti360Scripts/tree/master/kitti360scripts/devkits/convertOxtsPose
