### ISSUE TITLE
Missing scans in 2013_05_28_drive_0002_sync

### ISSUE THREAD

**Issue by miryalkarakshay** [autonomousvision/kitti360Scripts#92]
Hello,

After downloading and running the KITTI-360 download script. I observed that there are about 4,380 scans (00 to 4390) missing in the 2013_05_28_drive_0002_sync sequence. 

Were they removed from the sequence for a reason? 

Thanks,
Akshay Miryalkar

**Comment by ywang-zju** [comment]
Hi Akshay, these frames are renamed as  2013_05_28_drive_0018_sync for the purpose of split training and testing frames.

**Comment by yiyiliao** [comment]
Hi Akshay, we renamed the first 4380 frames of 2013_05_28_drive_0002_sync as 2013_05_28_drive_0018_sync to split training and test sequences.
